spring:
  application:
    name: jasypt
  # DB 연결
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: ENC(3Pp+yzTIl6sfZTJiXPGysw==)
    password: ENC(7/e8M3+ZJ3kHExDSHbYPEQj4u+fLwDXk)
  # jpa
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO_VALUE} # entity가 바뀐경우에는 update, 그외에는 validate 그리고 실제 배포시엔 validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
jasypt:
  encryptor:
    bean: jasyptStringEncryptor