spring:
  application:
    name: jasypt
  # DB ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: ENC(3Pp+yzTIl6sfZTJiXPGysw==)
    password: ENC(7/e8M3+ZJ3kHExDSHbYPEQj4u+fLwDXk)
  # jpa
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
jasypt:
  encryptor:
    bean: jasyptStringEncryptor